[package]
name = "filecoin"
description = "FFI Interface to Filecoin"
version = "0.7.3"
authors = ["laser <l@s3r.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/filecoin-project/filecoin-ffi"
readme = "README.md"
edition = "2018"
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
filecoin-proofs = { git = "https://github.com/filecoin-project/rust-fil-proofs.git", branch = "master" }
storage-proofs = { git = "https://github.com/filecoin-project/rust-fil-proofs.git", branch = "master" }
bls-signatures = { git = "https://github.com/filecoin-project/bls-signatures.git", branch = "master" }
byteorder = "1.2"
drop_struct_macro_derive = "0.4.0"
ff = "0.5"
ffi-toolkit = "0.4.0"
libc = "0.2.58"
log = "0.4.7"
paired = "0.16.0"
fil_logger = "0.1.0"
rand = "0.7"
rayon = "1"
anyhow = "1.0.23"

[build-dependencies]
cbindgen = "= 0.10.0"

[dev-dependencies]
tempfile = "3.0.8"
