header = """
/* filecoin Header */

#ifdef __cplusplus
extern "C" {{
#endif
"""
trailer = """
#ifdef __cplusplus
} /* extern "C" */
#endif
"""

include_guard = "FILECOIN_H"
include_version = true
language = "C"

[parse]
parse_deps = true
include = ["ffi-toolkit"]
