version: '3.7'

volumes:
  textile-fc-data:
  textile-fc-ipfs:
  textile-fc-lotus:

services:
  
  powergate:
    build:
      context: ../
      dockerfile: exe/server/Dockerfile
    ports:
      - 8889:8889
      - 8888:8888
      - 6060:6060
      - 5002:5002
      - 6002:6002
    depends_on:
      - ipfs
      - lotus
    environment:
      - TEXPOWERGATE_LOTUSHOST=/dns4/lotus/tcp/1235
      - TEXPOWERGATE_IPFSAPIADDR=/dns4/ipfs/tcp/5001
      - TEXPOWERGATE_LOTUSTOKENFILE=/root/lotus/.lotus/token
      - TEXPOWERGATE_REPOPATH=/root/powergate/.powergate
    restart: unless-stopped
    volumes:
      - textile-fc-data:/root/powergate
      - textile-fc-lotus:/root/lotus
  
  lotus:
    image: textile/lotus:799f5e5
    volumes:
      - textile-fc-lotus:/data
    ports:
      - 1235:1235
      - 5678:5678
    restart: unless-stopped

  ipfs:
    image: ipfs/go-ipfs:v0.5.0-rc2
    ports:
      - 5001:5001
    volumes:
      - textile-fc-ipfs:/data/ipfs
    restart: unless-stopped    
    
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
    restart: unless-stopped

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
       - '--port=8082'
    ports:
      - 8082:8082
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: unless-stopped

