version: '3.7'

volumes:
   pow-embed-shared:

services:
  
  powergate:
    build:
      context: ../
      dockerfile: exe/server/Dockerfile
    ports:
      - 8889:8889
      - 8888:8888
      - 6060:6060
      - 5002:5002
      - 6002:6002
    depends_on:
      - ipfs
      - lotus
    environment:
      - TEXPOWERGATE_EMBEDDED=true
      - TEXPOWERGATE_LOTUSHOST=/dns4/lotus/tcp/7777
      - TEXPOWERGATE_IPFSAPIADDR=/dns4/ipfs/tcp/5001
    volumes:
      - pow-embed-shared:/tmp/powergate
    restart: unless-stopped

  ipfs:
    image: ipfs/go-ipfs:v0.5.0-rc2
    ports:
      - 5001:5001

  lotus:
    image: textile/lotus-devnet:sha-03b4818
    ports:
      - 7777:7777
    environment:
      - TEXLOTUSDEVNET_SPEED=1500
    volumes:
     - pow-embed-shared:/tmp/powergate
