name: Tests
on:
  push:
    branches:
      - jsign/calib.8.13.0
  pull_request:
    branches:
      - master
jobs:
  test:
    name: compile & test
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Compile CLI on Windows
        run: GOOS=windows go build ./cmd/pow
      - name: Test
        run: make test
